version: 0.0
os: linux
files:
  - source: /FinalPro
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
    - location: scripts/update_db.sh
      timeout: 300
      runas: root
