version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Preparing files...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'appspec.yml'
    - 'FinalPro/**/*'
    - 'scripts/**/*'
  name: web-deployment-artifact
